version: 0.0
os: linux
files: 
  - source: /
    destination: /home/ec2-user/
hooks:
  AfterInstall:
    - location: /home/ec2-user/dist/scripts/afterInstallScript.sh
      timeout: 300
      runas: root
  ApplicationStop:
      - location: /home/ec2-user/dist/scripts/applicationStopScript.sh
        timeout: 300
        runas: root